---
- name: Precheck (skip unreachable hosts)
  hosts: all
  become: true
  gather_facts: false
  serial: "{{ patch_serial | default(10) }}"

  tasks:
    - name: Quick connectivity check
      ping:
      register: ping_out
      ignore_unreachable: true
      ignore_errors: true

    - name: End host if unreachable
      meta: end_host
      when: ping_out is failed

    - name: Gather minimal facts
      setup:
        gather_subset:
          - "!all"
          - "min"
      register: facts_out
      ignore_errors: true

    - name: End host if facts failed
      meta: end_host
      when: facts_out is failed

    - name: Show OS info
      debug:
        msg: "Host={{ inventory_hostname }} OS={{ ansible_facts.distribution }} {{ ansible_facts.distribution_version }} Family={{ ansible_facts.os_family }}"

