- name: Ensure reboot-check tooling exists
  hosts: all
  become: true
  gather_facts: true

  tasks:
    - name: Install needs-restarting (RHEL/Rocky/CentOS/Fedora)
      when: ansible_os_family in ["RedHat", "Fedora"]
      package:
        name: dnf-utils
        state: present
      failed_when: false

