---
- name: Patch Linux fleet (skip bad hosts, continue others)
  hosts: all
  become: true
  gather_facts: false
  serial: "{{ patch_serial | default(10) }}"

  vars:
    retries: "{{ patch_retries | default(3) }}"
    delay: "{{ patch_retry_delay | default(10) }}"

  tasks:
    - name: Connectivity check
      ping:
      register: ping_out
      ignore_unreachable: true
      ignore_errors: true

    - name: Skip host if unreachable
      meta: end_host
      when: ping_out is failed

    - name: Gather minimal facts
      setup:
        gather_subset:
          - "!all"
          - "min"
      register: facts_out
      ignore_errors: true

    - name: Skip host if facts failed
      meta: end_host
      when: facts_out is failed

    - name: Debian/Ubuntu - update + dist-upgrade
      apt:
        update_cache: yes
        cache_valid_time: 3600
        upgrade: dist
        autoremove: yes
      when: ansible_facts.os_family == "Debian"
      register: apt_out
      until: apt_out is succeeded
      retries: "{{ retries }}"
      delay: "{{ delay }}"
      ignore_errors: true

    - name: RHEL/Rocky/CentOS/Fedora - update all packages
      dnf:
        name: "*"
        state: latest
        update_cache: yes
      when: ansible_facts.os_family in ["RedHat", "Fedora"]
      register: dnf_out
      until: dnf_out is succeeded
      retries: "{{ retries }}"
      delay: "{{ delay }}"
      ignore_errors: true

    # Reboot detection (Debian)
    - name: Debian/Ubuntu - check reboot-required flag
      stat:
        path: /var/run/reboot-required
      when: ansible_facts.os_family == "Debian"
      register: deb_reboot
      ignore_errors: true

    # Reboot detection (RHEL family)
    - name: RHEL/Fedora - check if needs-restarting exists
      command: command -v needs-restarting
      when: ansible_facts.os_family in ["RedHat", "Fedora"]
      register: has_needs_restarting
      changed_when: false
      failed_when: false

    - name: RHEL/Fedora - needs-restarting -r (exit 1 => reboot needed)
      command: needs-restarting -r
      when:
        - ansible_facts.os_family in ["RedHat", "Fedora"]
        - has_needs_restarting.rc == 0
      register: rhel_reboot_check
      changed_when: false
      failed_when: false

    - name: Set reboot_required fact
      set_fact:
        reboot_required: >-
          {{
            (ansible_facts.os_family == "Debian" and (deb_reboot.stat.exists | default(false))) or
            (ansible_facts.os_family in ["RedHat","Fedora"] and (has_needs_restarting.rc == 0) and (rhel_reboot_check.rc | default(0)) == 1)
          }}
      ignore_errors: true

    - name: Show patch status
      debug:
        msg: >-
          Patched={{ inventory_hostname }}
          reboot_required={{ reboot_required | default(false) }}
          apt_rc={{ apt_out.rc | default('n/a') }}
          dnf_rc={{ dnf_out.rc | default('n/a') }}

