- name: Patch Linux hosts safely
  hosts: all
  gather_facts: true
  become: true
  serial: 1

  vars:
    reboot_if_required: true

  tasks:
    - name: Patch Debian/Ubuntu
      when: ansible_os_family == "Debian"
      block:
        - name: Update apt cache
          apt:
            update_cache: yes
            cache_valid_time: 3600

        - name: Upgrade packages
          apt:
            upgrade: dist

        - name: Check reboot required (Debian/Ubuntu)
          stat:
            path: /var/run/reboot-required
          register: reboot_required_deb

    - name: Patch RHEL/CentOS/Rocky/Fedora
      when: ansible_os_family in ["RedHat", "Fedora"]
      block:
        - name: Upgrade packages (dnf/yum)
          package:
            name: "*"
            state: latest

        - name: Check reboot required (RHEL-like)
          command: needs-restarting -r
          register: reboot_check_rhel
          failed_when: false
          changed_when: false

    - name: Decide if reboot is needed
      set_fact:
        do_reboot: >-
          {{
            (ansible_os_family == "Debian" and (reboot_required_deb.stat.exists | default(false)))
            or
            (ansible_os_family in ["RedHat","Fedora"] and (reboot_check_rhel.rc | default(1)) == 1)
          }}

    - name: Reboot if required
      when: reboot_if_required and do_reboot
      reboot:
        reboot_timeout: 1800
        pre_reboot_delay: 5
        post_reboot_delay: 10

    - name: Wait for SSH after reboot
      when: reboot_if_required and do_reboot
      wait_for_connection:
        delay: 5
        timeout: 600

    - name: Print kernel after patching
      command: uname -r
      changed_when: false
      register: kernel_after

    - debug:
        msg: "Kernel after patch: {{ kernel_after.stdout }}"

