- name: Patch Kubernetes nodes with drain/uncordon
  hosts: k8s_nodes
  gather_facts: true
  become: true
  serial: 1

  vars:
    kubeconfig_path: /etc/kubernetes/admin.conf

  pre_tasks:
    - name: Cordon node
      delegate_to: "{{ groups['k8s_master'][0] }}"
      command: kubectl --kubeconfig {{ kubeconfig_path }} cordon {{ inventory_hostname }}
      changed_when: true

    - name: Drain node (ignore daemonsets)
      delegate_to: "{{ groups['k8s_master'][0] }}"
      command: >
        kubectl --kubeconfig {{ kubeconfig_path }} drain {{ inventory_hostname }}
        --ignore-daemonsets --delete-emptydir-data --force
      register: drain_out
      failed_when: false
      changed_when: true

  tasks:
    - name: Patch this node
      import_playbook: 10-patch-linux.yml

  post_tasks:
    - name: Uncordon node
      delegate_to: "{{ groups['k8s_master'][0] }}"
      command: kubectl --kubeconfig {{ kubeconfig_path }} uncordon {{ inventory_hostname }}
      changed_when: true

