---
- name: Reboot nodes if needed
  hosts: all
  become: true
  gather_facts: false
  serial: 5

  tasks:
    - name: Skip unreachable quickly
      ping:
      register: ping_out
      ignore_unreachable: true
      ignore_errors: true

    - name: End host if unreachable
      meta: end_host
      when: ping_out is failed

    - name: Reboot if reboot_required is true
      reboot:
        reboot_timeout: 1800
        test_command: whoami
      when: reboot_required | default(false) | bool
      ignore_errors: true

    - name: Wait for SSH after reboot
      wait_for_connection:
        timeout: 600
      when: reboot_required | default(false) | bool
      ignore_errors: true

